# Intro til Numpy

## Fra matematiske funksjonsuttrykk til python-kode

__Læringsmål__:
* Bli kjent med numpy-typen ndarray
* Kune bruke arrays til å utføre elementvise beregninger

**Oversikt:**
* a) deklarasjon av arrays
* b) elementvis utregning
* c) arrays og funksjoner
* d) mer elementvis utregning
  
NB! Denne oppgaven bes du ikke om å lage funksjoner, men heller variabler med et spesifikkt navn.

## Importering av `numpy`-biblioteket

Numpy er noe som kalles et bibliotek. Dette er kode skrevet for å løse et problem som du kan ta i bruk i din egen kode. Numpy er laget for å gjøre numerikk i python mye lettere. Når man ønsker å bruke et bibliotek må man først fortelle til python at man skal bruke det, det gjør man med å *importere* biblioteket.

In [1]:
import numpy
import numpy as np
from numpy import cos, sin

Ovenfor ser du 3 forskjellige måter å importere funksjonalitet fra biblioteket på. Om du har et prosjekt som bare trenger en veldig liten del av et bibliotek kan det være en fordel å bruke den nederste. Da blir bare relevante funksjoner lastet inn, og du kan skrive navnet direkte istedenfor å måtte skrive `np.cos` eller `np.sin`.

Ellers bruker vi nesten alltid den i midten. Den er ekvivalent med den øverste, men gjør at man slipper å skrive så mye når man bruker biblioteket. Den sier til python at vi ønsker å bruke biblioteket numpy, og vi kaller det for *np*.

## Bruk av biblioteker

Om du ønsker å bruke den nederste linjen til å importere er det veldig lett å bruke funksjonalitetene. Da kaller du funksjonene du har importert som du ville gjort til vanlig. Dette kan gjøre python-program som regner ut matteformler mye lettere å lese.

In [2]:
from numpy import cos, sin

value = 0.7
sin_value = sin(value)
cos_value = cos(value)

print(f"Sin of {value} is {sin_value}")
print(f"Cos of {value} is {cos_value}")

Sin of 0.7 is 0.644217687237691
Cos of 0.7 is 0.7648421872844885


Når vi bruker bibliotek med hjelp av *import numpy as np* gjøres dette relativt likt. Eneste forskjellen er at vi må si til python at vi ønsker å bruke numpy biblioteket med *np.* slik som vist nedenfor.

In [3]:
import numpy as np

value = 0.7
sin_value = np.sin(value)
cos_value = np.cos(value)

print(f"Sin of {value} is {sin_value}")
print(f"Cos of {value} is {cos_value}")

Sin of 0.7 is 0.644217687237691
Cos of 0.7 is 0.7648421872844885


## Numpy-array

Numpy har også noen datatyper som vi kan bruke, og en av de mest vanlige er ndarray (kort for N-dimensjonal array). Dette er litt som en liste, men med funksjonalitet laget for numerikk. Det er også viktig å merke seg at indeksering, slicing, ol er likt som med vanlige lister.

Nedenfor ser du hvordan du lager en slik array.

In [4]:
import numpy as np

my_array = np.array([1, 2, 3])
print(my_array)

[1 2 3]


In [5]:
print(my_array[1])

2


## a) deklarasjon av arrays

Bruk funksjonen `numpy.array` til å lage en array `n` med tallverdiene $0,\ 1,\ 2,\ 3,\ 4\ \text{og}\ 5$ i den rekkefølgen
$$n \in \{0, 1, 2, 3, 4, 5\}$$

In [6]:
# SKRIV DIN KODE HER:
n = np.array([0, 1, 2, 3, 4, 5])

In [8]:
print(f"n: {n}")

n: [0 1 2 3 4 5]


## Regneoperasjoner med numpy array

Det som er spesielt for nympy-arrays er hvordan matematiske operasjoner funker på arrays. Med arrays vil nemlig operasjoner være *elementvis*, noe som vil si at operasjoner vil virke på hvert element hver for seg, istedenfor på hele arrayen. Nedenfor bruker vi my_array fra forrige kodecelle $n \in \{1, 2, 3\}$

In [9]:
my_array * 2

array([2, 4, 6])

In [10]:
my_array - 7

array([-6, -5, -4])

Med denne egenskapen kan man også gjøre vanskeligere operasjoner mulig. Ta for eksempel funksjonen nedenfor
$$x_{k} = \frac{1}{2}\cdot k^2 + 2\cdot k -3, \ \ \ \ \ k \in \{0, 1, 2, 3, 4, 5, 6 ,7 ,8, 9\}$$

Denne kan bli gjort relativt enkelt med numpy.

In [11]:
k = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
xa_k = k**2/2 + 2*k - 3
print(xa_k)

[-3.  -0.5  3.   7.5 13.  19.5 27.  35.5 45.  55.5]


Vi ser her at addisjon `+`, subtraksjon `-` og potensoperasjonen `**` utfører de aktuelle matematiske utregningene på _hvert element_ i array-variabelen `n`.

Dette lar oss utføre rimelig kompliserte og store utregninger med relativt få linjer. Tabellen nedenfor gir en forklaring på hvilke matematiske operatorer som støttes med numpy sine `ndarray` typer:

|Operator | Forklaring|
|---|---|
|+ | Elementvis Addisjon|
|- | Elementvis Subtraksjon|
|* | Elementvis Multiplikasjon|
|** | Elementvis Potensregning|

Når vi bruker numpy sine funksjoner vil også disse kunne brukes på arrays. 

In [12]:
from numpy import sin, cos, sqrt, pi

arr = np.array([pi, 4, 9])
print(sin(arr))
print(cos(arr))
print(sqrt(arr))

[ 1.22464680e-16 -7.56802495e-01  4.12118485e-01]
[-1.         -0.65364362 -0.91113026]
[1.77245385 2.         3.        ]


## b) elementvis utregning

Med verdiene i arrayen `n` fra forrige oppgave, lag en ny array `x` med verdier gitt i uttrykket nedenfor.

$$x_n = 0.64^{\frac{n}{2}}, \ \ \ \ \ n \in \{0, 1, 2, 3, 4, 5\}$$

In [13]:
# SKRIV DIN KODE HER:
x = 0.64 ** (n / 2)

In [15]:
print(f"x_n: {x}")

x_n: [1.      0.8     0.64    0.512   0.4096  0.32768]


## c) arrays og funksjoner

Med verdiene i arrayen `n` fra forrige oppgave, lag en ny array `y` som følger sinussekvensen.
$$y_n = \cos \left( \frac{\pi \cdot n}{11} + \frac{\pi}{6} \right), \ \ \ \ \ n \in \{0, 1, 2, 3, 4, 5\}$$

Hint: nympy biblioteket har en konstant kalt pi

In [17]:
# SKRIV DIN KODE HER:
y = cos((pi * n / 11) + (pi / 6))

In [18]:
print(f"y_n: {y}")

y_n: [ 0.8660254   0.69007901  0.45822652  0.18925124 -0.09505604 -0.37166246]


**Flere sekvenser i ett uttrykk.**

Hittil har vi sett på tilfeller hvor vi en av operanden i en regneoperasjon er et enkelt tall, og den andre er en array. Men det er også fullt mulig at begge operander er en array, så lenge de har ***like dimensjoner***. 

Se for eksempel på kodesnutten nedenfor:
```python
x1 = np.array([1, 2, 3, 4, 5, 6])
x2 = np.array([6, 5, 4, 3, 2, 1])

x3 = x1/x2
```

Her vil hvert element i `x3` være resulatet av tilsvarende element i `x1` delt på tilsvarende element i `x2`. Med andre ord vil linjen `x3 = x1/x2` gjøre det samme som koden nedenfor:

```python
x3 = np.array([x1[0]/x2[0], 
               x1[1]/x2[1], 
               x1[2]/x2[2], 
               x1[3]/x2[3], 
               x1[4]/x2[4], 
               x1[5]/x2[5]])
```

## d) mer elementvis utregning

Bruk elementvis multiplikasjon til å lage en array `z` som er _produktet_ av `x`og `y` fra deloppgave __b__ og __c__).
$$z_n = x_n \cdot y_n, \ \ \ \ \ n \in \{0, 1, 2, 3, 4, 5\}$$

In [19]:
# SKRIV DIN KODE HER:
z = x * y

In [20]:
print(f"z_n: {z}")

z_n: [ 0.8660254   0.55206321  0.29326497  0.09689664 -0.03893496 -0.12178635]
